In [1]:
import xarray as xr
import numpy as np

In [10]:
data = xr.DataArray(
    np.random.normal(size=(12, 100, 180, 360)),
    dims=("t", "z", "y", "x"),
)
data = data.assign_coords(z=np.linspace(2, 998, 100))
data

<xarray.DataArray (t: 12, z: 100, y: 180, x: 360)>
array([[[[-9.45758543e-01,  1.21260213e+00,  2.27150800e+00, ...,
           7.95854444e-01, -1.03942301e+00, -6.80358456e-01],
         [-7.75627801e-02, -4.91897154e-01,  6.10731613e-03, ...,
           4.83985381e-01, -3.47220587e-01,  7.29186789e-01],
         [ 3.97790722e-01,  6.55999246e-01, -7.02643035e-01, ...,
           1.33041059e-01, -1.01756410e+00, -4.42009294e-01],
         ...,
         [ 7.92313377e-01, -6.04668004e-01,  1.65249817e+00, ...,
           3.14493813e-01,  2.30326031e-01,  5.51591665e-01],
         [ 6.55965392e-01, -2.23111330e+00, -1.16298742e+00, ...,
          -3.01551496e-01,  1.68187827e+00,  1.40875412e+00],
         [ 3.31209707e-01,  9.87309243e-01, -5.76381199e-01, ...,
          -1.26034764e+00, -1.95144491e+00,  7.92518622e-02]],

        [[ 3.08171476e-01, -4.44803225e-01, -2.16643239e-01, ...,
          -1.01594863e+00, -3.51193869e-01,  2.32585619e-01],
         [-4.38414631e-01,  2.85266727e-01,  5.00820742e-01, ...,
           1.02248617e+00,  5.77020331e-01, -3.78832321e-01],
         [ 2.34190743e-02,  1.36526588e+00, -1.27262046e+00, ...,
          -1.89143518e+00, -5.55499936e-01,  1.45331933e+00],
...
         [-1.36006675e+00, -6.10398777e-02,  3.99309142e-01, ...,
          -6.64460770e-01, -1.15540045e+00, -2.89987416e-01],
         [ 1.20214448e+00,  5.69214474e-01, -1.42829761e+00, ...,
           4.30173008e-02,  1.45783586e-01, -1.28093319e+00],
         [-5.83191076e-01, -1.35043673e+00,  6.26810523e-01, ...,
           2.26453315e-01, -2.00706850e+00, -4.48228551e-01]],

        [[ 5.73007537e-01, -1.07590706e+00,  8.39478504e-01, ...,
           1.73926369e+00, -1.03041283e-02, -4.20155104e-01],
         [-9.62880921e-01,  6.12860724e-01, -2.08029469e-01, ...,
          -4.81825545e-01,  3.03017988e-01,  7.57980149e-01],
         [ 8.20228290e-01, -1.11736457e-01, -2.57774014e-01, ...,
           7.51865828e-01,  1.27339321e+00,  1.02067847e-01],
         ...,
         [ 1.18565059e+00, -1.94235490e+00,  1.58732620e+00, ...,
           5.35646932e-01,  9.38543593e-02,  8.41072190e-01],
         [-7.10708121e-01, -8.57550393e-01, -2.12738599e+00, ...,
           2.26230954e-01,  9.81203910e-01, -5.22576054e-01],
         [-2.01081464e+00, -9.84366498e-01, -9.62933318e-01, ...,
          -5.25186641e-01, -4.88884930e-01, -2.09659663e-01]]]])
Coordinates:
  * z        (z) float64 2.0 12.06 22.12 32.18 42.24 ... 967.8 977.9 987.9 998.0
Dimensions without coordinates: t, y, x

In [20]:
data.interp(z=np.linspace(0, 500, 25), method="linear").isel(t=0, x=0, y=0)

<xarray.DataArray (z: 25)>
array([        nan, -1.10733521,  1.08350778, -1.22957385,  0.2526275 ,
        0.45381345, -0.17055213,  0.55689564,  0.12248017,  1.11180685,
        0.22332188,  0.3890565 ,  0.40415116, -0.54695892,  0.68890636,
       -0.77149718, -0.06776768,  2.50613819, -0.42903844, -0.00394479,
        0.21339373,  0.30974419,  0.94714389,  0.28345989, -1.15710311])
Coordinates:
  * z        (z) float64 0.0 20.83 41.67 62.5 83.33 ... 437.5 458.3 479.2 500.0

In [21]:
data.interp(z=np.linspace(0, -500, 25), method="linear").isel(t=0, x=0, y=0)

<xarray.DataArray (z: 25)>
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
Coordinates:
  * z        (z) float64 0.0 -20.83 -41.67 -62.5 ... -437.5 -458.3 -479.2 -500.0

In [14]:
(
    data
    .interp(z=np.linspace(0, 500, 25), method="linear")
    .isel(t=0, x=0, y=0)
    .differentiate("z")
)

<xarray.DataArray (z: 25)>
array([        nan,         nan, -0.00293373, -0.01994113,  0.0404013 ,
       -0.01015631,  0.00247397,  0.00703278,  0.01331787,  0.0024202 ,
       -0.01734601,  0.0043399 , -0.02246437,  0.00683412, -0.00538892,
       -0.01816018,  0.07866325, -0.0086705 , -0.06024199,  0.01541837,
        0.00752854,  0.01761   , -0.00063082, -0.05050193, -0.06914702])
Coordinates:
  * z        (z) float64 0.0 20.83 41.67 62.5 83.33 ... 437.5 458.3 479.2 500.0

In [15]:
data.interp(z=xr.DataArray(np.linspace(0, 500, 25), dims=("depth", )), method="linear")

<xarray.DataArray (t: 12, depth: 25, y: 180, x: 360)>
array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan]],

        [[-1.10733521e+00, -1.38374947e+00,  7.25482875e-01, ...,
          -1.14843359e+00,  9.97052349e-02, -1.05099716e+00],
         [-1.36699998e-01, -7.68023864e-01, -2.53931426e-01, ...,
           9.65821756e-01, -1.50377835e+00, -9.50945511e-01],
         [ 8.56524113e-01, -1.36130673e+00,  9.01015777e-01, ...,
           8.76578286e-01, -3.06574437e-01,  1.58962718e+00],
...
         [-9.21344154e-01, -9.84891335e-01,  7.03577797e-01, ...,
           1.58283910e+00, -8.14036255e-01, -8.68053783e-01],
         [-3.91052672e-01, -3.78758866e-01,  1.63539535e+00, ...,
          -2.74510405e-01, -8.28964605e-01,  1.00148425e+00],
         [-9.88864058e-01, -8.86588932e-01, -2.03083449e-01, ...,
          -3.18110754e-01, -2.68260453e-01, -9.88236593e-01]],

        [[-1.23495903e-01, -8.01545474e-01, -7.30458794e-01, ...,
           2.05028076e-01,  5.52516085e-01, -1.32119190e+00],
         [ 5.52079409e-01,  2.88903687e-01, -1.25147586e-01, ...,
          -1.14091490e+00, -3.27131503e-01,  3.97843325e-01],
         [ 6.40179402e-01, -7.28447290e-01, -5.73451939e-01, ...,
           5.21221359e-01,  9.38833994e-01, -7.03366453e-01],
         ...,
         [-1.18037536e+00, -2.25795885e-01, -7.37443518e-01, ...,
           4.31590598e-01, -2.62352826e-01, -1.36000581e+00],
         [ 2.35583778e-01, -4.03125242e-01,  5.53858930e-02, ...,
          -3.02837377e-01, -1.65563842e-01,  1.94044282e-01],
         [-7.30035976e-01, -7.14286900e-01,  6.64590776e-01, ...,
          -5.07055730e-01, -1.21628071e+00,  2.92737870e-01]]]])
Coordinates:
    z        (depth) float64 0.0 20.83 41.67 62.5 ... 437.5 458.3 479.2 500.0
Dimensions without coordinates: t, depth, y, x

In [18]:
(
    data
    .interp(z=xr.DataArray(np.linspace(0, 500, 25), dims=("depth", )), method="linear")
    .isel(t=0, x=0, y=0)
    .differentiate("depth")
)

<xarray.DataArray (depth: 25)>
array([        nan,         nan, -0.06111932, -0.41544014,  0.84169365,
       -0.21158981,  0.0515411 ,  0.14651615,  0.2774556 ,  0.05042086,
       -0.36137517,  0.09041464, -0.46800771,  0.1423776 , -0.11226913,
       -0.37833702,  1.63881768, -0.18063538, -1.25504149,  0.32121608,
        0.15684449,  0.36687508, -0.01314215, -1.0521235 , -1.440563  ])
Coordinates:
    z        (depth) float64 0.0 20.83 41.67 62.5 ... 437.5 458.3 479.2 500.0
Dimensions without coordinates: depth

In [36]:
data.isel(z=slice(0, 1)) + data.isel(z=slice(7, 8))

SyntaxError: invalid syntax (1364245933.py, line 1)

In [44]:
data.sel(z=slice(333.4, 700)).diff("z") / data.sel(z=slice(333.4, 700)).z.diff("z")

<xarray.DataArray (t: 12, z: 36, y: 180, x: 360)>
array([[[[ 1.33835469e-01,  1.67976832e-02,  6.15367210e-02, ...,
          -1.97988750e-01, -4.95157113e-02, -2.03819451e-01],
         [ 2.95659654e-02, -1.46349886e-01, -5.87147598e-02, ...,
          -6.23949790e-02,  5.00158083e-02, -7.45005828e-02],
         [-2.73006609e-01, -9.78302749e-02, -1.69388218e-01, ...,
          -1.35207077e-01,  1.43563273e-01, -1.58439582e-01],
         ...,
         [-1.49701045e-02,  1.53238556e-01,  9.83446380e-03, ...,
           1.86600439e-01,  7.24268167e-02,  1.50309222e-01],
         [-1.58867314e-01,  4.86593799e-02,  1.63498167e-01, ...,
          -2.79923432e-01,  1.63880512e-02,  2.36185202e-01],
         [-9.72912630e-02, -3.27095382e-02, -4.72768331e-02, ...,
           7.96846554e-02, -1.55416155e-01, -2.11493114e-01]],

        [[ 1.19551210e-01,  1.42783565e-03, -1.57340051e-01, ...,
           1.14719817e-01,  6.90557828e-02,  4.19589433e-03],
         [-1.78419699e-01, -1.77187043e-01,  2.63018849e-02, ...,
           6.50394972e-02,  2.75098985e-01,  4.48375136e-02],
         [ 2.02514252e-01, -1.16451470e-01,  1.74367431e-01, ...,
          -4.32809198e-02, -2.16309285e-01,  1.28751487e-01],
...
         [ 2.65002069e-01, -1.51082828e-01, -2.26768303e-01, ...,
          -1.15241263e-01, -2.84784071e-01, -2.13127699e-01],
         [ 3.51326622e-03,  1.00576541e-02, -1.01527552e-01, ...,
           7.53970350e-02, -1.90988596e-01,  1.41684489e-01],
         [-3.72345904e-01, -2.12592276e-01,  3.33719998e-01, ...,
          -7.79039394e-02, -9.06473808e-02,  1.82849221e-01]],

        [[-6.58779257e-02, -1.61963542e-01, -4.55870637e-02, ...,
          -4.22935209e-01, -3.22706012e-02,  3.57115741e-02],
         [-9.64435608e-02,  9.51565769e-02,  1.18324373e-01, ...,
          -1.48126995e-01, -6.18845854e-02, -5.53709050e-02],
         [ 1.64467611e-01,  8.75076188e-02,  4.07911595e-02, ...,
          -5.17939007e-02,  4.45694376e-03, -2.72240414e-01],
         ...,
         [-2.16497505e-01,  4.87524224e-02,  1.74314019e-01, ...,
           3.98994433e-01,  3.38937596e-01,  1.05714877e-01],
         [ 2.87971559e-02,  3.97324318e-04,  9.38275753e-02, ...,
          -7.40775255e-02,  8.50395980e-02, -7.81254059e-02],
         [ 2.82408445e-01,  2.01724486e-01, -3.02444242e-01, ...,
          -1.49549106e-01, -7.96203036e-02,  2.66268307e-02]]]])
Coordinates:
  * z        (z) float64 344.1 354.1 364.2 374.2 ... 666.0 676.1 686.1 696.2
Dimensions without coordinates: t, y, x

In [35]:
np.array([1, 2, 3, 4])[slice(1, 3)]

array([2, 3])

In [27]:
# (data.isel(z=0, drop=True) * data.z)[:, 4, :, :]
(data.z * data.isel(z=0, drop=True))[:, 4, :, :] * data.z

<xarray.DataArray (z: 100, y: 180, x: 360)>
array([[[ 1.28624796e+00,  4.19928722e+00, -2.29799715e-01, ...,
         -6.33349675e+00, -2.59160137e+00, -7.53424837e-01],
        [-2.96338082e+00, -2.27104136e-01, -5.68840652e-01, ...,
          8.40546972e+00, -2.73985419e+00,  2.18270642e+00],
        [ 2.30750345e+00, -3.28198236e+00,  6.06851430e+00, ...,
          8.58894413e-01,  1.87786770e-01, -8.83748454e+00],
        ...,
        [ 3.88868232e+00,  4.87274044e+00,  1.89686653e+00, ...,
          9.92249204e-02, -4.92839744e+00,  8.52914781e-01],
        [-4.91176825e+00, -4.18876027e+00,  1.22591360e+00, ...,
          8.38552050e+00, -7.32785383e-01, -9.61903758e+00],
        [-5.35823012e+00, -4.96656336e+00,  6.51230646e+00, ...,
         -1.63568170e+00, -1.18278990e+00, -8.50793098e-01]],

       [[ 4.67738343e+01,  1.52705210e+02, -8.35656429e+00, ...,
         -2.30314789e+02, -9.42424297e+01, -2.73979587e+01],
        [-1.07762024e+02, -8.25854077e+00, -2.06856370e+01, ...,
          3.05661163e+02, -9.96335775e+01,  7.93731469e+01],
        [ 8.39113351e+01, -1.19347827e+02,  2.20678820e+02, ...,
          3.12333128e+01,  6.82878227e+00, -3.21371189e+02],
...
        [ 9.48862057e+05,  1.18897820e+06,  4.62846932e+05, ...,
          2.42114820e+04, -1.20255885e+06,  2.08116377e+05],
        [-1.19850122e+06, -1.02208290e+06,  2.99130349e+05, ...,
          2.04611783e+06, -1.78804075e+05, -2.34710348e+06],
        [-1.30744063e+06, -1.21187156e+06,  1.58904225e+06, ...,
         -3.99116249e+05, -2.88607905e+05, -2.07598673e+05]],

       [[ 3.20277029e+05,  1.04562672e+06, -5.72203588e+04, ...,
         -1.57704703e+06, -6.45311333e+05, -1.87603538e+05],
        [-7.37884788e+05, -5.65491570e+04, -1.41641891e+05, ...,
          2.09297037e+06, -6.82226434e+05,  5.43496082e+05],
        [ 5.74570665e+05, -8.17216891e+05,  1.51106613e+06, ...,
          2.13865568e+05,  4.67590936e+04, -2.20054249e+06],
        ...,
        [ 9.68285786e+05,  1.21331724e+06,  4.72321663e+05, ...,
          2.47071044e+04, -1.22717589e+06,  2.12376633e+05],
        [-1.22303520e+06, -1.04300550e+06,  3.05253712e+05, ...,
          2.08800299e+06, -1.82464293e+05, -2.39514998e+06],
        [-1.33420466e+06, -1.23667924e+06,  1.62157082e+06, ...,
         -4.07286378e+05, -2.94515868e+05, -2.11848332e+05]]])
Coordinates:
  * z        (z) float64 2.0 12.06 22.12 32.18 42.24 ... 967.8 977.9 987.9 998.0
Dimensions without coordinates: y, x