In [1]:
import xarray as xr
import numpy as np

In [2]:
# parameters
num_nodes = 11_000
num_neighbors = 10
len_time = 400
len_z = 40

In [3]:
n = xr.DataArray(
    np.arange(num_nodes, ),
    dims=("n", ),
    name="n",
)
n

<xarray.DataArray 'n' (n: 11000)>
array([    0,     1,     2, ..., 10997, 10998, 10999])
Dimensions without coordinates: n

In [4]:
neighbors = xr.DataArray(
    np.arange(num_neighbors),
    dims=("j", ),
    name="neighbor",
)

In [5]:
z = xr.DataArray(
    np.arange(len_z),
    dims=("z", ),
    name="z",
)
z

<xarray.DataArray 'z' (z: 40)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])
Dimensions without coordinates: z

In [6]:
groups = (
    n.isel(n=slice(None, None, num_neighbors))
    + neighbors
)
groups

<xarray.DataArray (n: 1100, j: 10)>
array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [10970, 10971, 10972, ..., 10977, 10978, 10979],
       [10980, 10981, 10982, ..., 10987, 10988, 10989],
       [10990, 10991, 10992, ..., 10997, 10998, 10999]])
Dimensions without coordinates: n, j

In [7]:
T = xr.DataArray(
    np.random.normal(size=(num_nodes, len_time, len_z)),
    dims=("n", "t", "z"),
    name="temp",
    coords={"n": n, "z": z},
)
T

<xarray.DataArray 'temp' (n: 11000, t: 400, z: 40)>
array([[[ 5.66862608e-01, -4.86865259e-01, -2.81926598e-02, ...,
         -4.39078625e-01,  5.47368999e-01,  2.52072544e+00],
        [-1.92119401e+00, -5.26378993e-02,  2.63471622e-01, ...,
         -1.78654727e-01, -3.88606686e-01, -2.75461202e-01],
        [ 1.80489086e+00, -1.74591102e-01,  3.94153520e-01, ...,
          5.95568765e-01,  4.14119707e-01, -9.14597172e-01],
        ...,
        [ 1.64709992e-01,  2.71441026e-01, -1.90916237e-01, ...,
         -4.94731589e-01,  7.42328474e-01,  9.73665244e-01],
        [-9.41775648e-01,  2.46521236e+00, -3.08668973e-01, ...,
         -1.29961702e-01, -1.01007240e+00,  4.54615614e-01],
        [-6.63307827e-01, -6.50213093e-01, -1.08460567e+00, ...,
          8.16190604e-01,  5.21211780e-01, -7.80832862e-01]],

       [[-2.89716230e-01,  6.87015081e-01,  8.00310350e-01, ...,
         -1.86170426e+00, -1.27954909e+00, -1.74256608e-03],
        [-3.70889575e-01,  1.29405365e+00, -7.54600295e-01, ...,
         -3.89111690e-02, -2.03177141e-01, -8.92073940e-01],
        [ 4.43028168e-01,  6.53430431e-03, -2.89882492e-01, ...,
          1.82640490e-01,  3.55573733e-01, -3.36534046e-01],
...
        [-1.83224038e+00, -1.26238930e-01, -5.13008647e-01, ...,
          1.01862918e+00,  7.53655348e-01,  1.43940632e+00],
        [ 1.18507314e-01, -1.01943267e+00,  1.11410485e+00, ...,
         -7.20517394e-01,  3.38788268e-02, -1.08598476e+00],
        [-3.34266070e-01,  1.03740762e+00, -2.29142651e-01, ...,
         -1.61593823e+00, -3.68483561e-01,  5.38897272e-01]],

       [[ 2.15228044e-01, -1.49368762e+00,  2.28520015e-01, ...,
         -2.15720070e-01, -1.85524241e-01,  8.71915352e-02],
        [-8.92312184e-01, -2.39204225e-01,  1.93910195e-01, ...,
          6.88571084e-01, -2.21775218e+00,  3.95412012e-01],
        [-7.68765116e-01, -6.05792755e-01,  9.29431703e-01, ...,
          5.31525594e-01, -1.69137724e-02, -2.39570955e-01],
        ...,
        [-1.05406341e-01,  1.76726360e+00,  4.52614184e-02, ...,
          6.69503773e-02, -3.30600224e-01, -9.04731689e-01],
        [ 5.46818614e-02, -5.55437902e-02, -1.62788735e-01, ...,
          7.51413457e-01, -1.10973585e-02, -2.63759748e+00],
        [ 1.08469914e+00, -1.80274898e+00,  1.07438034e-01, ...,
          6.76022625e-02,  2.28678436e-01,  4.93870496e-01]]])
Coordinates:
  * n        (n) int64 0 1 2 3 4 5 6 ... 10994 10995 10996 10997 10998 10999
  * z        (z) int64 0 1 2 3 4 5 6 7 8 9 10 ... 30 31 32 33 34 35 36 37 38 39
Dimensions without coordinates: t

In [8]:
W = xr.ones_like(n * neighbors)
W = W.assign_coords(n=n)
W

<xarray.DataArray (n: 11000, j: 10)>
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])
Coordinates:
  * n        (n) int64 0 1 2 3 4 5 6 ... 10994 10995 10996 10997 10998 10999
Dimensions without coordinates: j

In [9]:
(T * W).sel(n=groups).sum("j") / W.sel(n=groups).sum("j")

<xarray.DataArray (n: 1100, t: 400, z: 40)>
array([[[ 3.83960652e-01,  4.84468010e-01, -2.07341508e-02, ...,
         -7.18352160e-01, -3.72997080e-01,  1.29352208e-01],
        [-2.96771293e-01,  2.69518503e-01, -7.90498239e-02, ...,
          1.71815901e-01, -5.34040326e-01, -1.33536100e-01],
        [-1.93003647e-02, -4.77709706e-01, -3.18189684e-01, ...,
          4.19698405e-01, -2.36714525e-02, -3.63224904e-02],
        ...,
        [-4.95253257e-01, -2.42395906e-02, -7.99550667e-01, ...,
         -4.88667537e-01, -8.49290751e-01,  3.63014675e-02],
        [ 3.62272525e-02,  7.15422286e-01, -2.24405755e-01, ...,
         -1.11906779e+00,  2.94985106e-01, -4.19530554e-01],
        [ 2.26365500e-01, -6.17407567e-01,  1.29359280e-01, ...,
         -3.18202191e-01, -2.23472501e-01, -3.78974753e-01]],

       [[ 1.05376401e-01,  3.22524113e-01, -9.28396287e-02, ...,
          1.16918921e-01,  2.94175027e-01, -6.60228141e-02],
        [-3.50501280e-01, -1.13144273e-01, -1.54048166e-03, ...,
          1.28394966e-01, -6.85122776e-02, -6.09478050e-02],
        [-1.14895756e-01,  3.67399137e-01, -6.33945796e-02, ...,
         -3.62206608e-01, -1.70480761e-01,  4.12366869e-01],
...
        [ 9.13210560e-02, -3.75234592e-01,  3.90206637e-01, ...,
         -2.63432822e-01, -3.47883152e-01, -3.81486359e-01],
        [ 2.31059928e-01,  8.88565211e-02, -6.15829610e-01, ...,
          2.09109025e-01, -6.10717352e-02,  5.67564711e-01],
        [ 6.40027080e-01, -2.84113118e-01,  2.70819618e-02, ...,
         -1.11955227e-01,  9.05602393e-02, -4.34927071e-01]],

       [[ 6.27814379e-02, -7.84509419e-02,  1.64460237e-01, ...,
          1.39507451e-01,  3.00304825e-01,  1.28808904e-01],
        [-7.00036435e-01, -3.33312209e-01, -5.43282416e-01, ...,
          3.39449399e-01, -2.28505663e-01,  1.73408781e-03],
        [-2.52428517e-01, -1.73619816e-01, -9.04548450e-03, ...,
          1.48197248e-01, -9.80214570e-02,  6.14263823e-02],
        ...,
        [-1.19463284e-01, -2.65929979e-01, -2.84405434e-02, ...,
         -2.10095206e-01, -2.91144136e-01, -3.92408034e-02],
        [ 9.41210127e-02, -8.34267432e-02,  1.12910196e-01, ...,
          2.65017426e-01,  3.89301714e-01,  3.93754602e-02],
        [-1.93189459e-01,  5.17396395e-02, -1.88216907e-01, ...,
         -2.93376561e-01,  2.37811603e-01,  3.17711090e-01]]])
Coordinates:
  * z        (z) int64 0 1 2 3 4 5 6 7 8 9 10 ... 30 31 32 33 34 35 36 37 38 39
Dimensions without coordinates: n, t